Fixing docker-compose example
Removing storageEngine reference since it's not supported
```
ERROR: no such image: mongo:latest+--storageEngine=wiredTiger: invalid reference format
```